apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      name: backend-app
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend
          image: khaled30/node-backend
          ports:
            - containerPort: 8000
          resources:
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongo-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongo-password
            - name: MONGO_URL
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo-service:27017/app-db?authSource=admin"
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-port
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - port: 8000
      targetPort: 8000
