apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backed-app
  template:
    metadata:
      name: backed-app
      labels:
        app: backed-app
    spec:
      containers:
        - name: backend
          image: khaled30/node-backend
          ports:
            - containerPort: 8000
          resources:
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: mongo-url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-port
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
    - port: 8000
      targetPort: 8000
