apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      name: mongo-app
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          resources:
          # env:
          #   - name: MONGO_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: app-secret
          #         key: mongo-username
          #   - name: MONGO_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: app-secret
          #         key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo-app
  ports:
    - port: 27017
      targetPort: 27017
