apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-sts
  labels:
    app: mongo-sts
spec:
  replicas: 1
  serviceName: mongo-service
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      name: mongo-app
      labels:
        app: mongo-app
    spec:
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongo-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongo-password
            - name: MONGO_INITDB_DATABASE
              value: "app-db"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo-app
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    app: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
