apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: my-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
    - port: 80
      targetPort: 80
