---
apiVersion: v1
kind: Namespace
metadata:
  name: my-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: nginx-pod
  namespace: my-ns
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-service
  namespace: my-ns
spec:
  type: LoadBalancer
  selector:
    app: nginx-pod
  ports:
    - port: 80
      targetPort: 80
