---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 3
  selector:
    app: nginx-pod
  template:
    metadata:
      name: my-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
    - port: 80
      targetPort: 80
