apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-pod # pod label
  ports:
    - port: 80
      targetPort: 80
